// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adxrtzvbenbpbnqaulrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkeHJ0enZiZW5icGJucWF1bHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzg4MzcsImV4cCI6MjA2MDIxNDgzN30.KFzEKBUfMsZRVFmavvApHUNtYQ3gx1rFcQOJKF3tUvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);